<a href="https://colab.research.google.com/github/GitHub-Harshita/MachineLearningAlgorithms/blob/main/Sequential.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SEQUENTIAL MODEL

In [ ]:
import numpy as np

In [ ]:
X = np.array([
    [2, 5],
    [4, 6],
    [6, 7],
    [8, 8]])
y = np.array([40, 60, 75, 90])

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential([
    Dense(8, activation="relu",input_shape=([2])),
    Dense(1)
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer="adam", loss="mse")

In [ ]:
model.fit(X,y,epochs=300)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 717ms/step - loss: 5233.6182
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 5225.7852
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 5217.9595
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 5210.1387
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5202.3242
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5194.5161
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5186.7144
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5178.9189
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5171.1304
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5163.3477
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5155.5713
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5147.8013
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5140.0366
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5132.2783
Epoch 15/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 4

In [ ]:
model.predict(np.array([[7,8]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


array([[19.208132]], dtype=float32)

Ye jo 20 predict kiya h isne ye galat kiya hai kyuki model humara uderfit h, mtlb ki model hmara bhaut simple h ki isne pdhna hi strt nhi kiya h

KYUKI YE CONFUSE H KI DATA KO konsi range me lu x vle data ki ya y vle data ki, to hume isko scale krna pdega 0 se 1 ke bich me, taki ye ache se sikh paye

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
Scaler_X=MinMaxScaler()
Scaler_y=MinMaxScaler()

In [ ]:
scaled_X=Scaler_X.fit_transform(X)

In [ ]:
scaled_y=Scaler_y.fit_transform(y.reshape(-1,1)) #reshape isiliye kiya kyuki keras ko 2d data chahiye hota h or y hmara 1d h, isme -1 ka mtlb ye khud calculate krega no. of rows or 1 mtlb 1 column

In [ ]:
model.fit(scaled_X, scaled_y, epochs=300)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.0073
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.0066
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0060
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0055
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0049
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.0045
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0040
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.0037
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 0.0033
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.0030
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0028
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0026
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0024
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0023
Epoch 15/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0022
Epoch 16/300
1/1 ━━━━

In [ ]:
pred=model.predict(Scaler_X.transform([[7,8]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


In [ ]:
pred

array([[0.95106405]], dtype=float32)

In [ ]:
pred_original=Scaler_y.inverse_transform(pred)

In [ ]:
pred_original

array([[87.5532]], dtype=float32)

bt haaa, agr maxminscaler use krna h to use direct flow me use krna, aise mt krna ki phle bina maxminscaler use kre run kr diya fr glt prediction aayi to fr dobara usi trained model ko minmaxscaer ke sath train kr diya vrna fr glt output aayega


LINEAR REGRESSION

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()

In [ ]:
import numpy as np
X=np.array([
    [1,2],
    [2,4],
    [3,6],
    [4,8],
    [5,10]
])
y=np.array([3,6,9,12,15])

In [ ]:
model.fit(X,y)

LinearRegression()

In [ ]:
model.predict([[6,12]])

array([18.])

LOGISTIC REGRESSION

In [ ]:
import numpy as np

In [ ]:
X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6]])
y=np.array([0,0,0,1,1,1])

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(X,y)

LogisticRegression()

In [ ]:
model.predict([[7]])

array([1])